# Generated by Django 5.2.15 on 2026-09-14 08:32
#
# Restores the AnalyticView model/table dropped by 0124_delete_analyticview
# (in-app Analytics dashboard feature removal, since reverted at the user's
# request). Kept as a new forward migration rather than deleting 0124,
# since 0124 was already applied against the live database — this
# recreates the table instead of rewriting migration history.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0124_delete_analyticview"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticView",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("query", models.JSONField()),
                ("query_dict", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytic",
                "verbose_name_plural": "Analytics",
                "db_table": "analytic_views",
                "ordering": ("-created_at",),
            },
        ),
    ]
